name = "JuliaCrash"
uuid = "9016c9a2-a34e-4334-80a7-0e0ecb54d19c"
authors = ["Olivier Verdier <olivier.verdier@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Manifolds = "1cead3c2-87b3-11e9-0ccd-23c62b72b94e"

[compat]
Manifolds = "0.10.3"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
